### PR TITLE
Support `add`, `update` and `delete` mutations

### PR DESCRIPTION
**Pull request by tothandras**
```
mutation updateFriendsList {
  updateUser(input: {id: "VXNlcjo1NjBlODc4MWQ0OTRkN2ZlMjIxZDM0MjA=", name: "Jane Doe", clientMutationId: "1"}) {
    name
    id
    friends {
      edges {
        cursor
        node {
		  id
		  name
        }
      }
      pageInfo {
        startCursor
        endCursor
        hasPreviousPage
      	hasNextPage
      }
    }
  }
}

```
response:
```json
{
  "data": {
    "updateUser": {
      "name": "Jane Doe",
      "id": "VXNlcjo1NjBlODc4MWQ0OTRkN2ZlMjIxZDM0MjA=",
      "friends": {
        "edges": [
          {
            "cursor": "Y29ubmVjdGlvbi41NjBlODc4MWQ0OTRkN2ZlMjIxZDM0MjE=",
            "node": {
              "id": "VXNlcjo1NjBlODc4MWQ0OTRkN2ZlMjIxZDM0MjE=",
              "name": "testName2"
            }
          }
        ],
        "pageInfo": {
          "startCursor": "Y29ubmVjdGlvbi41NjBlODc4MWQ0OTRkN2ZlMjIxZDM0MjE=",
          "endCursor": "Y29ubmVjdGlvbi41NjBlODc4MWQ0OTRkN2ZlMjIxZDM0MjE=",
          "hasPreviousPage": true,
          "hasNextPage": false
        }
      }
    }
  }
}
```

There are a more examples in the `e2e.spec.js` test file.

### CODE REVIEW

**Comment by tothandras** [comment]
@hardchor I am not sure how the mutations work exactly in Relay and what kind of mutations (update, add, delete) have to be handled. Can you help me?

**Comment by tothandras** [comment]
Can I merge this? @hekike

**Comment by hekike** [comment]
@tothandras yes. Shouldn't we provide an option to disable/enable mutation queries? I think it can be dangerous until we don't provide solutions for authorisation.

**Comment by tothandras** [comment]
@hekike Okay, I'll add this option before merging.

**Pull request merged**
