### PR TITLE
feat(query): add support for query by reference

### PR DESCRIPTION
**Pull request by choyongjoon**
It's for the issue https://github.com/RisingStack/graffiti-mongoose/issues/103
I referenced schema.js
https://github.com/RisingStack/graffiti-mongoose/blob/master/src/schema/schema.js#L113

### CODE REVIEW

**Comment by tothandras** [comment]
Looks good! Can you add at least one test case?

**Comment by choyongjoon** [comment]
I've tried to make a test. But I got test errors.
Can you check it and show me the way?

https://github.com/choyongjoon/graffiti-mongoose/commit/0b76253262a29c9f0a3f7cb794368e8e87ec6e99

**Comment by tothandras** [comment]
We should probably create end-to-end (`e2e.spec.js`) tests first.
I was playing with the model in #103.
1.
```
mutation AddForum {
  addForum(input: {title: "foo", clientMutationId: "1"}) {
    changedForumEdge {
      node {
        id
      }
    }
  }
}
```
2.
```
mutation AddTopic {
  addTopic(input: {title: "bar", clientMutationId: "2", uuid: "uuid", forum: "id from previous response"}) {
    changedTopicEdge {
      node {
        id
      }
    }
  }
}
```
3.
```
query TopicsByForum{
  topics(forum: "this with mongoose ObjectId, but it doesn't with GraphQL ID") {
    forum {
      id
      _id
      title
    }
  }
}

# error
"Cast to ObjectId failed for value \"Rm9ydW06NTcyNzlkM2RjNWQ2MDg3NTBkN2E5YzM4\" at path \"forum\""
```
The reason that it can't accept GraphQL ID is that [here](https://github.com/RisingStack/graffiti-mongoose/blob/master/src/query/query.js#L105) we only convert the `id` or `_id` fields from GraphQL to mongoose ID. We need to process all fields with something like:
`selector = mapValues(selector, (field) => processId({id: field}));`.

**Comment by developer-rakeshpaul** [comment]
@tothandras any luck on this PR?

**Pull request closed without merging**
