### PR TITLE
Support query, mutation hooks

### PR DESCRIPTION
**Pull request by tothandras**
```javascript
const hooks = {
  viewer: {
    pre: (next, root, args, {rootValue}) => {
      const {request} = rootValue;
      // authorize the logged in user based on the request
      authorize(request);
      // modify arguments ...
      // args.id = 'userid';
      next(root, args, {rootValue});
    },
    post: (next, value) => {
      console.log(value);
      next();
    }
  },
  singular: {
    pre: (next, root, args, {rootValue}) => next(),
    post: (next, value) => next()
  },
  plural: {
    pre: (next, root, args, {rootValue}) => next(),
    post: (next, value) => next()
  },
  mutation: {
    pre: (next, args, {rootValue}) => next(),
    post: (next, value) => next()
  }
};
const schema = getSchema(models, {hooks});
```

### CODE REVIEW

**Comment by hekike** [comment]
lgtm

Are you planning to add an example hook to the todo app? For example console log when an item was marked as resolved.

**Comment by tothandras** [comment]
@hekike
can dooo

**Comment by burkhardr** [comment]
Would you not pass `value` through to `next(value)` in your `post` hooks?

**Comment by tothandras** [comment]
@burkhardr You can pass a value, in that case the next middleware will get it, otherwise it gets the default arguments.

**Comment by burkhardr** [comment]
Brilliant! LGTM :shipit:

**Pull request merged**
