### PR TITLE
Support for custom resolve write and read middleware

### PR DESCRIPTION
**Pull request by tothandras**
- [x] documentation
- [ ] examples

### CODE REVIEW

**Comment by tothandras** [comment]
Please review! :)
@hekike, @hardchor

**Comment by hekike** [comment]
@tothandras lgtm, only one thing, wouldn't be good idea to add a Schema level hook as well?

**Comment by tothandras** [comment]
@hekike I was thinking about it, but currently I don't have a good way in mind to implement it.

**Comment by hekike** [comment]
@tothandras ok sure keep it for future prs. This one looks good to me.

**Comment by hardchor** [comment]
As @hekike has mentioned, schema-level hooks would probably make a little more sense in most use cases. Is there no easy way?

**Comment by hardchor** [comment]
From our discussion just then:

Rather than the hooks approach, why won't we expose middleware on a more global level (e.g. in `getSchema` and further upstream). Middleware could then look like this:

```javascript
{
  resolve: {
    pre: (...) => {},
    post: (...) => {},
  },
  // singular?
  get: { 
    pre: (params, etc) => {},
    post: (...) => {},
  },
  // plural?
  list: {
    pre: (params, etc) => {},
    post: (...) => {},
  },
  mutate: {
    pre: (action, params, etc) => {},
    post: (...) => {},
  },
}
```

**Pull request merged**
