### PR TITLE
Add arguments to connections based on the fields of the type

### PR DESCRIPTION
**Pull request by tothandras**

### CODE REVIEW

**Comment by tothandras** [comment]
@hardchor What do you think?

**Comment by hardchor** [comment]
Hate to be a pain in the backside, but some unit tests would be good ;)

Other than that: LGTM :shipit:

**Comment by tothandras** [comment]
You are absolutely right! :) I am always asking for the same...

**Comment by tothandras** [comment]
@hardchor I've added a test, is it good enough? :)

**Comment by hardchor** [comment]
Yeah, that'll do :+1:

**Comment by tothandras** [comment]
merged

**Pull request closed without merging**
