### PR TITLE
getProjections implementation with inline fragments support

### PR DESCRIPTION
**Pull request by gyzerok**
For now its just a raw implementation without tests.

Can you describe in details what are requirements for testing? I have some troubles with testing.

### CODE REVIEW

**Comment by gyzerok** [comment]
What do you think about somehow test utils code with original GraphQL queries?

**Comment by hekike** [comment]
@gyzerok wow, thanks. Later today I'll dig deeper to understand it.
About tests, we have:

- unit tests like https://github.com/RisingStack/graffiti-mongoose/blob/master/src/utils.spec.js
- e2e tests like https://github.com/RisingStack/graffiti-mongoose/blob/master/src/e2e.spec.js

In unit tests we stub external dependencies, but not graphql and still using graphql queries because would be hard to test otherwise.

In e2e tests we are reading and writing to real MongoDB and using the public interfaces of the `graffiti-mongoose.`.

**Comment by gyzerok** [comment]
@hekike For now I'm trying to generate test for this functionality. So its a working on PR. I know that it works since i'm using it [here](https://github.com/gyzerok/redux-react-graphql-example).

**Comment by gyzerok** [comment]
To understand it consider query:
```javascript
`{
  user(_id: "12345") {
    ... on User {
      name
    }
  }
}`
```

This PR currently is work in progress, so do not merge it for now.

**Comment by hekike** [comment]
@gyzerok ok thanks, I put `[WIP]` (work in progress) to title, please remove when you feel it's ready to merge

**Comment by gyzerok** [comment]
@hekike Ok, right now I'm waiting for your feedback after reviewing PR.

**Comment by hekike** [comment]
@gyzerok seems to be good for me. Only one question about `.babelrc`. Will it work for the `prepublish` hook in `package.json` as well? Have you checked it?

**Comment by gyzerok** [comment]
@hekike Yes, it works. If all is ok for you and enough covered with tests, I think its ready to be merged.

**Comment by hekike** [comment]
@gyzerok thank you, I'll release it soon!

**Pull request merged**
