### PR TITLE
Update graphql-js to latest

### PR DESCRIPTION
**Pull request by tothandras**
- graphql-js: 0.4.4
- fix tests

### CODE REVIEW

**Comment by tothandras** [comment]
I have tried to add support for Object types. @hekike, please review!

**Comment by hekike** [comment]
@tothandras what you mean under try? :) Is it working and covered with tests?

**Comment by tothandras** [comment]
Right, the tests are passing. :)

**Comment by hekike** [comment]
@tothandras it sounds for me more than trying :D
I'll check it soon and merge.

**Comment by tothandras** [comment]
thanks

**Pull request merged**
